name: Test compiler

on:
  push:
    paths: ['rivetc/**.py']
    branches: [main]

jobs:
  build-compiler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rivet source code
        uses: actions/checkout@v2

      - name: Install CMake & LLVM
        run: |
          sudo apt-get install pip3
          sudo pip3 install llvmlite

      - name: Run compiler
        run: |
          python3 ./rivetc.py --help
