name: Self-hosted compiler

on:
  push:
  
jobs:
  windows-clang:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile self-hosted compiler
        run: |
          python3 rivetc -bc clang -o rivet cmd/
          ./rivet version
          ./rivet build cmd/

  ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile self-hosted compiler
        run: |
          python3 rivetc -bc clang -o rivet cmd/
          ./rivet version
          ./rivet build cmd/
  
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile self-hosted compiler
        run: |
          python3 rivetc -bc gcc -o rivet cmd/
          ./rivet version
          ./rivet build cmd/
