name: Test compiler

on:
  push:
    paths: ['lib/**.ri', 'src/**.py', 'tests/**.ri']
    branches: [main]

jobs:
  ubuntu-clang:
    runs-on: ubuntu-latest
    env:
      RIVET_CC_TEST: clang
    steps:
      - name: Checkout Rivet source code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          python3 tests/run_ok_tests.py

      - name: Run failing tests
        run: |
          python3 tests/run_failing_tests.py

  ubuntu-gcc:
    runs-on: ubuntu-latest
    env:
      RIVET_CC_TEST: gcc
    steps:
      - name: Checkout Rivet source code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          python3 tests/run_ok_tests.py

      - name: Run failing tests
        run: |
          python3 tests/run_failing_tests.py

  windows-msvc:
    runs-on: windows-2019
    env:
      RIVET_CC_TEST: msvc
    steps:
      - name: Checkout Rivet source code
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          python3 tests/run_ok_tests.py

      - name: Run failing tests
        run: |
          python3 tests/run_failing_tests.py

  windows-gcc:
    runs-on: windows-2019
    env:
      RIVET_CC_TEST: gcc
    steps:
      - name: Checkout Rivet source code
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          python3 tests/run_ok_tests.py

      - name: Run failing tests
        run: |
          python3 tests/run_failing_tests.py
