name: Test compiler

on:
  push:
    paths: ['src/**.py', 'rivetc.py', 'tests/**.ri']
    branches: [main]

jobs:
  test-compiler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rivet source code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          python3 tests/run_ok_tests.py

      - name: Run failing tests
        run: |
          python3 tests/run_failing_tests.py
